### PR TITLE
Add GNS networking implementation

### PR DESCRIPTION
**Pull request by Ceron257**
This adds the possibility to switch between steamworks' and Valve's GameNetworkingSockets implementation during development by defining the constant `USE_DEV_NET`. 

`GameNetworkingSockets/ValveSockets.cs` is basically the C# binding from Valve extended by `LoadNativeDll()` which loads the GNS binaries. These binaries would have to be built by everyone as there's no binary release. We might however add some prebuilt binaries according to GNS's license.

Please feel free to give any feedback or refactor the code as needed.

### CODE REVIEW

**Comment by zuev93** [comment]
Looks better and better! :)

First question:
What do you think about extracting GameNetworkingSockets to a separate repo and reference it via nuget?
In my opinion it shouldn't be a part of the mod (it is quite generic and can be used in other project).

**Comment by Ceron257** [comment]
Very good idea. However I would have to first learn how to do such things. Especially when it comes to questions like: How to package native libraries with a nuget package? And how to handle native libraries bundled in a nuget package correctly?

Also the way how the native library is currently provided, loaded and used really isn't that simple and intuitive and that would have to be changed to get a package that could easily be used. I am not sure if I could come up with a good solution in a reasonable amount of time due to my lack of expertise in that area.

**Comment by Ceron257** [comment]
I'm fine with that. Probably I'm not going to work on this in the foreseeable future. At least it's relatively easy to use to hopefully enable more contributions.

Maybe it makes sense to create an issue for this and mention the suggestions there.

**Review by zuev93 — APPROVED** [review]
Created #103 to cover mentioned points.

Also, since this will be merged into a separate branch - consider updating README/CONTRIBUTING in the main branch.

**Pull request merged**
